# Generated by Django 5.2.15 on 2026-07-06 14:26

import automations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='repetition',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='schedule',
        ),
        migrations.AddField(
            model_name='automation',
            name='crontab',
            field=models.CharField(default='0 0 * * *', help_text='Crontab expression, e.g. "0 9 * * 1" for every Monday at 09:00.', max_length=100, validators=[automations.models.validate_crontab]),
        ),
    ]
