# Generated by Django 5.2.15 on 2026-07-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_remove_automation_repetition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='next_run',
        ),
    ]
